
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects { project ->
    if (project.name != 'app') {
        project.afterEvaluate {
            if (project.hasProperty('android')) {
                project.android {
                    if (namespace == null) {
                        namespace project.group.toString().isEmpty() ? "com.example.${project.name}" : project.group
                    }
                    compileSdkVersion 35
                    println "Configured subproject :${project.name} with compileSdkVersion 35 and namespace ${namespace}"
                }
            }
        }
    }
}

subprojects { project ->
    if (project.name != 'app') {
        evaluationDependsOn(':app')
    }
}

allprojects {
    configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.core' && 
                (details.requested.name == 'core' || details.requested.name == 'core-ktx')) {
                details.useVersion '1.13.1'
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
